### ISSUE TITLE
go install error

### ISSUE THREAD

**Issue by wogong** [erdnaxe/miniflux-luma#1] opened 2023-07-27 03:06 UTC
I am not familiar with go, I tried `go install` and got this error.

```
# github.com/erdnaxe/miniflux-luma
./miniflux-luma.go:31:14: cannot use true (untyped bool constant) as string value in struct literal
```

**Comment by erdnaxe** [comment] 2023-07-27 15:09
This is a bug caused by a little API change in Miniflux client module: https://github.com/miniflux/v2/commit/fb585d0086c55a51f6d09ad68ba0219a4be86252

I need to replace `true` by `"1"`.

**Comment by erdnaxe** [comment] 2023-07-27 15:13
Fixed by https://github.com/erdnaxe/miniflux-luma/commit/21cbb2d53f1f6e14f245b51f9d01a8ac0dc92c55

**Closed by erdnaxe** 2023-07-27 15:13 UTC
